[project]
name = "ise-record"
version = "1.2.0"
requires-python = "~=3.14"

dependencies = [
    "aiofiles~=25.1",
    "aiosmtplib~=5.1",
    "email-validator~=2.3",
    "fastapi~=0.141",
    "httpx2~=2.13",
    "pathvalidate~=3.3",
    "pydantic-settings~=2.15",
    "PyJWT[crypto]~=2.15",
    "PyOTP~=2.10",
    "python-multipart~=0.0",
    "uvicorn~=0.54",
]

[dependency-groups]
test = [
    "pytest~=9.1",
    "pytest-asyncio~=1.4",
    "pytest-mock~=3.15",
]

dev = [
    { include-group = "test" },
    "fastapi[standard]",
    "pylint~=4.0",
    "ruff~=0.16"
]

[build-system]
requires = ["setuptools >= 84.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"ise_record" = [ "**/py.typed", "py.typed" ]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.pyright]
useLibraryCodeForTypes = true

[tool.fastapi]
entrypoint = "ise_record.server:app"
