name: Frontend tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-node@v6
      with:
        node-version: '24.x'

    - name: Install dependencies
      working-directory: ${{ github.workspace }}/frontend
      run: |
        npm install
        sudo npx playwright install-deps
        npx playwright install

    - name: Run linter
      continue-on-error: true
      working-directory: ${{ github.workspace }}/frontend
      run: |
        npm run lint

    - name: Test Frontend (Firefox)
      # has trouble running on the forgejo ci in my cheap VM, so just run on github ci for now
      if: runner.environment == "github-hosted"
      working-directory: ${{ github.workspace }}/frontend
      run: |
        npm run test -- --project=firefox --no-file-parallelism --test-timeout=30000

    - name: Test Frontend (Chromium)
      working-directory: ${{ github.workspace }}/frontend
      run: |
        npm run test -- --project=chromium --no-file-parallelism --test-timeout=30000
