name: Backend tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get -y install ffmpeg

    - name: Install python dependencies
      working-directory: ${{ github.workspace }}/backend
      run: |
        pip install -e . --group dev

    - name: Run linter
      continue-on-error: true
      working-directory: ${{ github.workspace }}/backend
      run: |
        pylint .

    - name: Test Backend
      working-directory: ${{ github.workspace }}/backend
      run: |
        pytest
