name: Frontend tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-node@v6
      with:
        node-version: '24.x'

    - name: Install dependencies
      working-directory: ${{ github.workspace }}/frontend
      run: |
        npm install
        npx playwright install --only-shell chromium

    - name: Install dependencies (github-exclusive)
      if: runner.environment == 'github-hosted'
      working-directory: ${{ github.workspace }}/frontend
      run: |
        npx playwright install firefox

    - name: Run linter
      continue-on-error: true
      working-directory: ${{ github.workspace }}/frontend
      run: |
        npm run lint

    - name: Test Frontend (Chromium)
      working-directory: ${{ github.workspace }}/frontend
      run: |
        npm run test -- --project chromium

    - name: Test Frontend (Firefox)
      if: runner.environment == 'github-hosted'
      working-directory: ${{ github.workspace }}/frontend
      run: |
        npm run test -- --project firefox
